import { HttpClient, HttpParams } from '@angular/common/http';
import { inject, Injectable, InjectionToken } from '@angular/core';
import { map, Observable } from 'rxjs';
import { API_BASE_URL } from '../../../core/api/api.config';
import { LaravelDataResponse, LaravelPaginatedResponse } from '../../../core/api/models/api-response.models';
export interface GameDrawDto {id:string;game_id:string;game_number_id:string;sequence:number;drawn_number:number;strategy:string;drawn_at:string;}
export interface GameCounterDto {game_number_id:string;number:number;status:string;hits_count:number;last_draw_sequence:number|null;}
export interface DrawResultDto {game_id:string;draw_id:string;game_number_id:string;sequence:number;drawn_number:number;current_hits:number;hits_required:number;number_is_sold:boolean;winner_created:boolean;winner_entry_id:string|null;game_status:string;drawn_at:string;replay:boolean;}
export interface WinnerDto {winner_id:string;game_id:string;game_entry_id:string;game_number_id:string;winning_number:number|null;game_draw_id:string;winning_draw_sequence:number|null;winning_hits:number;user_id:number;won_at:string;}
export interface EngineCommandDto {game_id:string;status?:string;outcome:string;started_at?:string;paused_at?:string;resumed_at?:string;next_draw_at?:string;confirmed_entries_count?:number;}
export interface GameEngineRepository {command(id:string,action:'start'|'pause'|'resume'):Observable<EngineCommandDto>;draw(id:string,commandId:string):Observable<DrawResultDto>;draws(id:string):Observable<GameDrawDto[]>;counters(id:string):Observable<GameCounterDto[]>;winner(id:string):Observable<WinnerDto>;rebuild(id:string):Observable<unknown>;}
export const GAME_ENGINE_REPOSITORY=new InjectionToken<GameEngineRepository>('GAME_ENGINE_REPOSITORY');
@Injectable() export class HttpGameEngineRepository implements GameEngineRepository {private readonly http=inject(HttpClient);private readonly base=inject(API_BASE_URL);command(id:string,action:'start'|'pause'|'resume'){return this.http.post<LaravelDataResponse<EngineCommandDto>>(`${this.base}/admin/games/${encodeURIComponent(id)}/${action}`,{}).pipe(map(r=>r.data));}draw(id:string,commandId:string){return this.http.post<LaravelDataResponse<DrawResultDto>>(`${this.base}/admin/games/${encodeURIComponent(id)}/draws`,{},{headers:{'X-Draw-Command-Id':commandId}}).pipe(map(r=>r.data));}draws(id:string){return this.http.get<LaravelPaginatedResponse<GameDrawDto>>(`${this.base}/admin/games/${encodeURIComponent(id)}/draws`,{params:new HttpParams().set('per_page',100)}).pipe(map(r=>r.data));}counters(id:string){return this.http.get<LaravelDataResponse<GameCounterDto[]>>(`${this.base}/admin/games/${encodeURIComponent(id)}/counters`).pipe(map(r=>r.data));}winner(id:string){return this.http.get<LaravelDataResponse<WinnerDto>>(`${this.base}/admin/games/${encodeURIComponent(id)}/winner`).pipe(map(r=>r.data));}rebuild(id:string){return this.http.post<LaravelDataResponse<unknown>>(`${this.base}/admin/games/${encodeURIComponent(id)}/counters/rebuild`,{}).pipe(map(r=>r.data));}}