import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { StatusBadge } from '../../../../shared/ui/status-badge/status-badge';
import { formatMoney } from '../../../public-games/utils/public-game-display';
import { AdminGamesFacade } from '../../data-access/admin-games.facade';
import { CreateAdminGameDto } from '../../models/admin-games.models';

@Component({
  selector:'app-admin-games-page',imports:[ReactiveFormsModule,StatusBadge],providers:[AdminGamesFacade],
  template:`<section class="page"><header class="page-header"><div><p class="eyebrow">Operación</p><h1>Bingos</h1><p>Crea partidas y controla el ciclo que ya expone Laravel.</p></div></header>
  @if(facade.error()){<p class="alert error" role="alert">{{facade.error()?.message}}</p>}@if(facade.message()){<p class="alert success" role="status">{{facade.message()}}</p>}
  <div class="layout"><form class="surface-card panel" [formGroup]="createForm" (ngSubmit)="create()"><div><h2>Crear bingo</h2><p>El nuevo juego se crea en estado borrador.</p></div><div class="fields"><label>Nombre<input formControlName="name"></label><label>Slug<input formControlName="slug" placeholder="noche-de-fortuna"></label><label class="wide">Descripción<textarea formControlName="description" rows="3"></textarea></label><label>Número mínimo<input type="number" formControlName="number_min"></label><label>Número máximo<input type="number" formControlName="number_max"></label><label>Aciertos requeridos<input type="number" formControlName="hits_required"></label><label>Precio en céntimos<input type="number" formControlName="ticket_price_cents"></label><label>Premio en céntimos<input type="number" formControlName="prize_cents"></label><label>Moneda<input formControlName="currency" maxlength="3"></label><label>Intervalo del sorteo (s)<input type="number" formControlName="draw_interval_seconds"></label><label class="check"><input type="checkbox" formControlName="auto_draw_enabled"> Sorteo automático</label><label>Inicio de ventas<input type="datetime-local" formControlName="sales_opens_at"></label><label>Cierre de ventas<input type="datetime-local" formControlName="sales_closes_at"></label><label>Inicio programado<input type="datetime-local" formControlName="scheduled_start_at"></label></div><button class="button" type="submit" [disabled]="createForm.invalid||facade.busy()">Crear bingo</button></form>
  <section class="surface-card panel"><div><h2>Operar un bingo</h2><p>Usa el UUID devuelto al crear o conocido desde la API.</p></div><label>ID del juego<input [formControl]="gameId" placeholder="UUID"></label><div class="actions"><button class="button button--secondary" type="button" [disabled]="!gameId.value||facade.busy()" (click)="transition('publish')">Publicar</button><button class="button button--secondary" type="button" [disabled]="!gameId.value||facade.busy()" (click)="transition('open-sales')">Abrir ventas</button><button class="button button--secondary" type="button" [disabled]="!gameId.value||facade.busy()" (click)="transition('close-sales')">Cerrar ventas</button><button class="button button--secondary" type="button" [disabled]="!gameId.value||facade.busy()" (click)="facade.loadNumbers(gameId.value)">Ver números</button></div><label>Programar inicio<input type="datetime-local" [formControl]="scheduledStart"></label><button class="button button--secondary" type="button" [disabled]="!gameId.value||!scheduledStart.value||facade.busy()" (click)="facade.schedule(gameId.value,scheduledStart.value)">Programar</button><label>Motivo de cancelación<textarea [formControl]="cancelReason" maxlength="500" rows="3"></textarea></label><button class="button button--danger" type="button" [disabled]="!gameId.value||facade.busy()" (click)="facade.cancel(gameId.value,cancelReason.value)">Cancelar bingo</button></section></div>
  @if(facade.game();as game){<section class="surface-card result"><div><small>Último juego actualizado</small><h2>{{game.name}}</h2><p>{{game.slug}} · {{game.number_range.min}}–{{game.number_range.max}} · {{game.number_range.hits_required}} aciertos</p></div><strong>{{money(game.prize.amount_cents,game.prize.currency)}}</strong><app-status-badge [tone]="game.status==='cancelled'?'danger':game.status==='sales_open'?'success':'info'">{{game.status}}</app-status-badge></section>}
  @if(facade.numbers().length){<section class="surface-card number-panel"><header><h2>Grilla administrativa</h2><p>Disponibilidad, reserva activa y participante confirmado.</p></header><div class="numbers">@for(item of facade.numbers();track item.id){<article [class.reserved]="item.active_reservation" [class.sold]="item.sold_entry"><strong>{{item.number}}</strong><small>{{item.sold_entry?.user_name||item.active_reservation?.order_status||item.status}}</small></article>}</div></section>}
  <p class="integration"><strong>Brecha conocida:</strong> Laravel todavía no expone un listado administrativo de juegos; por eso esta pantalla no inventa borradores ni métricas.</p></section>`,
  styles:`.layout{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(18rem,.8fr);gap:var(--s4)}.panel{display:grid;align-content:start;gap:var(--s4);padding:var(--s5)}.panel h2,.panel p{margin:.1rem 0}.panel p,.result p,.number-panel p{color:var(--color-text-muted)}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--s3)}label{display:grid;gap:.35rem;color:var(--color-text);font-size:var(--sm);font-weight:700}.wide{grid-column:1/-1}input,textarea{width:100%;min-height:2.7rem;padding:.65rem .75rem;border:1px solid var(--color-border);border-radius:var(--r-md);font:inherit}.check{display:flex;align-items:center}.check input{width:auto}.actions{display:grid;grid-template-columns:1fr 1fr;gap:var(--s2)}.alert,.integration{padding:var(--s3);border-radius:var(--r-md)}.error{background:#fff1f0;color:#b42318}.success{background:#ecfdf3;color:#067647}.result{display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:var(--s4);padding:var(--s5);margin-top:var(--s4)}.number-panel{padding:var(--s5);margin-top:var(--s4)}.numbers{display:grid;grid-template-columns:repeat(auto-fill,minmax(4rem,1fr));gap:.5rem}.numbers article{display:grid;min-height:4rem;place-items:center;padding:.35rem;border:1px solid var(--neutral-200);border-radius:var(--r-md);background:#fff}.numbers article.reserved{border-color:#f5b942;background:#fff8df}.numbers article.sold{border-color:#70c59a;background:#ecfdf3}.numbers small{text-align:center;color:var(--color-text-muted);font-size:.65rem}.integration{margin-top:var(--s4);background:var(--neutral-50);color:var(--color-text-muted);font-size:var(--sm)}@media(max-width:60rem){.layout{grid-template-columns:1fr}}@media(max-width:38rem){.fields{grid-template-columns:1fr}.wide{grid-column:auto}.result{grid-template-columns:1fr}.actions{grid-template-columns:1fr}}`,changeDetection:ChangeDetectionStrategy.OnPush})
export class AdminGamesPage{
  readonly facade=inject(AdminGamesFacade);readonly money=formatMoney;readonly gameId=new FormControl('',{nonNullable:true});readonly scheduledStart=new FormControl('',{nonNullable:true});readonly cancelReason=new FormControl('',{nonNullable:true,validators:[Validators.maxLength(500)]});
  readonly createForm=new FormGroup({slug:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.minLength(3),Validators.pattern(/^[a-z0-9-]+$/)]}),name:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(160)]}),description:new FormControl('',{nonNullable:true}),number_min:new FormControl(1,{nonNullable:true,validators:[Validators.required,Validators.min(1)]}),number_max:new FormControl(90,{nonNullable:true,validators:[Validators.required,Validators.min(2)]}),hits_required:new FormControl(5,{nonNullable:true,validators:[Validators.required,Validators.min(2)]}),ticket_price_cents:new FormControl(500,{nonNullable:true,validators:[Validators.required,Validators.min(0)]}),prize_cents:new FormControl(200000,{nonNullable:true,validators:[Validators.required,Validators.min(0)]}),currency:new FormControl('PEN',{nonNullable:true,validators:[Validators.required,Validators.pattern(/^[A-Za-z]{3}$/)]}),draw_interval_seconds:new FormControl(10,{nonNullable:true,validators:[Validators.required,Validators.min(1)]}),auto_draw_enabled:new FormControl(false,{nonNullable:true}),sales_opens_at:new FormControl('',{nonNullable:true}),sales_closes_at:new FormControl('',{nonNullable:true}),scheduled_start_at:new FormControl('',{nonNullable:true})});
  create(){if(this.createForm.invalid)return;const v=this.createForm.getRawValue();const iso=(x:string)=>x?new Date(x).toISOString():null;const dto:CreateAdminGameDto={...v,description:v.description.trim()||null,sales_opens_at:iso(v.sales_opens_at),sales_closes_at:iso(v.sales_closes_at),scheduled_start_at:iso(v.scheduled_start_at),currency:v.currency.toUpperCase(),settings:null};this.facade.create(dto);}
  transition(action:'publish'|'open-sales'|'close-sales'){const messages={publish:'Bingo publicado.','open-sales':'Ventas abiertas.','close-sales':'Ventas cerradas.'} as const;this.facade.transition(this.gameId.value,action,messages[action]);}
}